// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: createUser.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO user (clerk_user_id) VALUES (?)
`

func (q *Queries) CreateUser(ctx context.Context, clerkUserID string) error {
	_, err := q.db.ExecContext(ctx, createUser, clerkUserID)
	return err
}
