// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: savelongTrend.sql

package sqlc

import (
	"context"
)

const deleteLongTrend = `-- name: DeleteLongTrend :exec
DELETE FROM longtrends
`

func (q *Queries) DeleteLongTrend(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteLongTrend)
	return err
}

const getLongTrend = `-- name: GetLongTrend :many
SELECT trends_id, trends_name, trends_location, trends_months, trends_increase_percentage FROM longtrends
`

func (q *Queries) GetLongTrend(ctx context.Context) ([]Longtrend, error) {
	rows, err := q.db.QueryContext(ctx, getLongTrend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Longtrend{}
	for rows.Next() {
		var i Longtrend
		if err := rows.Scan(
			&i.TrendsID,
			&i.TrendsName,
			&i.TrendsLocation,
			&i.TrendsMonths,
			&i.TrendsIncreasePercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveLongTrend = `-- name: SaveLongTrend :exec
INSERT INTO longtrends (trends_name,trends_location,trends_months,trends_increase_percentage) VALUES (?, ?, ?, ?)
`

type SaveLongTrendParams struct {
	TrendsName               string `json:"trends_name"`
	TrendsLocation           string `json:"trends_location"`
	TrendsMonths             int32  `json:"trends_months"`
	TrendsIncreasePercentage int32  `json:"trends_increase_percentage"`
}

func (q *Queries) SaveLongTrend(ctx context.Context, arg SaveLongTrendParams) error {
	_, err := q.db.ExecContext(ctx, saveLongTrend,
		arg.TrendsName,
		arg.TrendsLocation,
		arg.TrendsMonths,
		arg.TrendsIncreasePercentage,
	)
	return err
}
